/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.13.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as client from "../client.js";
import type * as conversation from "../conversation.js";
import type * as conversationMembership from "../conversationMembership.js";
import type * as conversationMembership from "../conversationMembership.js";
import type * as ids from "..../wsserver.js
import type * as ids from "../ids.js";
import type * as index from "../index.js";
import type * as textInput from "../textInput.js";
import type * as textInput from "../textInput.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  client: typeof client;
  conversation: typeof conversation;
  conversationMembership: typeof conversationMembership;
  conversationMembership: typeof conversationMembership;
  ids: typeof ids;
  ids: typeof ids;
  index: typeof index;
  textInput: typeof textInput;
  textInput: typeof textInput;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
