/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.13.2.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as AgentMemory_agent from "../AgentMemory/agent.js";
import type * as AgentMemory_conversationMemory from "../AgentMemory/conversationMemory.js";
import type * as AgentMemory_embeddingsCache from "../AgentMemory/embeddingsCache.js";
import type * as AgentMemory_memoryHelper from "../AgentMemory/memoryHelper.js";
import type * as PerceptionAnalysis_extractEmotion from "../PerceptionAnalysis/extractEmotion.js";
import type * as PerceptionAnalysis_extractEvent from "../PerceptionAnalysis/extractEvent.js";
import type * as PerceptionAnalysis_extract_emotion from "../PerceptionAnalysis/extract_emotion.js";
import type * as PerceptionAnalysis_extract_event from "../PerceptionAnalysis/extract_event.js";
import type * as PerceptionAnalysis_needsExtraction from "../PerceptionAnalysis/needsExtraction.js";
import type * as actions from "../actions.js";
import type * as agentConversation from "../agentConversation.js";
import type * as agentConversationHelper from "../agentConversationHelper.js";
import type * as client from "../client.js";
import type * as constants from "../constants.js";
import type * as conversation from "../conversation.js";
import type * as conversationMembership from "../conversationMembership.js";
import type * as game from "../game.js";
import type * as ids from "../ids.js";
import type * as messages from "../messages.js";
import type * as server from "../server.js";
import type * as testing from "../testing.js";
import type * as tests_testChat from "../tests/testChat.js";
import type * as tests_testConversations from "../tests/testConversations.js";
import type * as tests_testExtractEmotion from "../tests/testExtractEmotion.js";
import type * as tests_testExtractEvent from "../tests/testExtractEvent.js";
import type * as tests_testInitializeAgents from "../tests/testInitializeAgents.js";
import type * as tests_testVision from "../tests/testVision.js";
import type * as textInput from "../textInput.js";
import type * as util_FastIntegerCompression from "../util/FastIntegerCompression.js";
import type * as util_assertNever from "../util/assertNever.js";
import type * as util_asyncMap from "../util/asyncMap.js";
import type * as util_compression from "../util/compression.js";
import type * as util_geometry from "../util/geometry.js";
import type * as util_inspectModel from "../util/inspectModel.js";
import type * as util_isSimpleObject from "../util/isSimpleObject.js";
import type * as util_llm from "../util/llm.js";
import type * as util_minheap from "../util/minheap.js";
import type * as util_object from "../util/object.js";
import type * as util_pythonServer from "../util/pythonServer.js";
import type * as util_sleep from "../util/sleep.js";
import type * as util_types from "../util/types.js";
import type * as util_xxhash from "../util/xxhash.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  "AgentMemory/agent": typeof AgentMemory_agent;
  "AgentMemory/conversationMemory": typeof AgentMemory_conversationMemory;
  "AgentMemory/embeddingsCache": typeof AgentMemory_embeddingsCache;
  "AgentMemory/memoryHelper": typeof AgentMemory_memoryHelper;
  "PerceptionAnalysis/extractEmotion": typeof PerceptionAnalysis_extractEmotion;
  "PerceptionAnalysis/extractEvent": typeof PerceptionAnalysis_extractEvent;
  "PerceptionAnalysis/extract_emotion": typeof PerceptionAnalysis_extract_emotion;
  "PerceptionAnalysis/extract_event": typeof PerceptionAnalysis_extract_event;
  "PerceptionAnalysis/needsExtraction": typeof PerceptionAnalysis_needsExtraction;
  actions: typeof actions;
  agentConversation: typeof agentConversation;
  agentConversationHelper: typeof agentConversationHelper;
  client: typeof client;
  constants: typeof constants;
  conversation: typeof conversation;
  conversationMembership: typeof conversationMembership;
  game: typeof game;
  ids: typeof ids;
  messages: typeof messages;
  server: typeof server;
  testing: typeof testing;
  "tests/testChat": typeof tests_testChat;
  "tests/testConversations": typeof tests_testConversations;
  "tests/testExtractEmotion": typeof tests_testExtractEmotion;
  "tests/testExtractEvent": typeof tests_testExtractEvent;
  "tests/testInitializeAgents": typeof tests_testInitializeAgents;
  "tests/testVision": typeof tests_testVision;
  textInput: typeof textInput;
  "util/FastIntegerCompression": typeof util_FastIntegerCompression;
  "util/assertNever": typeof util_assertNever;
  "util/asyncMap": typeof util_asyncMap;
  "util/compression": typeof util_compression;
  "util/geometry": typeof util_geometry;
  "util/inspectModel": typeof util_inspectModel;
  "util/isSimpleObject": typeof util_isSimpleObject;
  "util/llm": typeof util_llm;
  "util/minheap": typeof util_minheap;
  "util/object": typeof util_object;
  "util/pythonServer": typeof util_pythonServer;
  "util/sleep": typeof util_sleep;
  "util/types": typeof util_types;
  "util/xxhash": typeof util_xxhash;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
